// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'FirebaseOptions não configurado para iOS.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'FirebaseOptions não configurado para macOS.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'FirebaseOptions não configurado para Windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'FirebaseOptions não configurado para Linux.',
        );
      default:
        throw UnsupportedError(
          'FirebaseOptions não suportado nesta plataforma.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh52nchYBnxzWv8pon15JsLFVJXzfBfV8',
    appId: '1:316592305950:android:a283f707c155fb6d6abb0f',
    messagingSenderId: '316592305950',
    projectId: 'primeagenda-app',
    storageBucket: 'primeagenda-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYMc1NIj7Yvz_ylmfk3ycfdFj8rYdUrrw',
    appId: '1:316592305950:web:026f03c29b25463f6abb0f',
    messagingSenderId: '316592305950',
    projectId: 'primeagenda-app',
    authDomain: 'primeagenda-app.firebaseapp.com',
    storageBucket: 'primeagenda-app.firebasestorage.app',
  );
}